### ISSUE TITLE
Characteristic Warnings

### ISSUE THREAD

**Issue by thuelskamp** [steveredden/homebridge-kasa-lightstrip#4]
I started getting these every few minutes today. Everything seems functional but reporting it all the same. The errors still occurred at every stage of the following troubleshooting: Removed the accessory completely / made sure all cached devices were gone / reinstalled and ran without any custom effects / reinstalled the custom effects. 

Here is the debug log info:

[10/30/2021, 3:29:51 PM] [homebridge-kasa-lightstrip] This plugin generated a warning from the characteristic 'Hue': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[10/30/2021, 3:29:51 PM] [homebridge-kasa-lightstrip] Error: 
    at Hue.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2074:105)
    at Hue.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1967:16)
    at Hue.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1492:24)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

[10/30/2021, 3:29:51 PM] [homebridge-kasa-lightstrip] This plugin generated a warning from the characteristic 'Saturation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[10/30/2021, 3:29:51 PM] [homebridge-kasa-lightstrip] Error: 
    at Saturation.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2074:105)
    at Saturation.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1967:16)
    at Saturation.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1492:24)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10/30/2021, 3:29:51 PM] [LifxLan] LIFX 41c043 - Get power: 0

**Comment by JBruster1119** [comment]
Any updates on this?
